### ISSUE TITLE
"Open source" term is inaccurate

### ISSUE THREAD

**Issue by Nomagno** [BartMartner/OpenARNF#1]
Hello! It's extremely cool that you released the source code to the game, and I'm sure it'll result in very positive experiences and extremely nice mods.

However, this game is not "open source", at least not how that term is understood. "Open source" means a piece of software is released under an [Open Source Definition (OSD)](https://opensource.org/docs/osd) compatible license, and license.md has a noncommercial usage clause. This is perfectly reasonable, but disqualifies the license from meeting the definition, so it is not "open source".

To prevent misunderstandings, I suggest changing terminology (the repository name's fine as it is) to "source available", "released under a noncommercial license", or something of the sort

**Comment by orowith2os** [comment]
"Released under a noncommercial license" seems like a nice fit, rather than source available.

Alternatively, the game owner can copyright the branding and give requirements for when an end user can utilize it, and have the game itself be open source under a license such as the GPL (maybe LGPL?) as it requires any and all modifications to be made public. One such project doing something similar is [Inochi2D](https://github.com/Inochi2D/inochi-creator)

**Comment by imbev** [comment]
I also recommend the GPL

An explanation of the GPL - https://opensource.org/licenses/GPL-3.0

**Comment by BartMartner** [comment]
Hi! I wanted to let you all know I'm taking this into consideration. I've updated the [steam announcement](https://steamcommunity.com/app/603530/eventcomments/3361398331720139508?snr=2_9_100000_&ctp=3) and removed the language open source. I'll alter it in the read me as well.

I'm considering updating the license to one recommended (GPL and/or a truly [Open Source one](https://opensource.org/licenses).) Need to figure out how best to do that and the implications first.

**Comment by vazhnov** [comment]
Maybe reopening this task is a good idea to not forget about it.
We are waiting!
